// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/java/tc/oc/protobuf/packet/protocols/test_extending_message.proto

package tc.oc.protobuf.packet.protocols;

public final class TestExtendingMessage {
  private TestExtendingMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage.extendingMessage);
  }
  public interface ExtendingMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 numerical_value = 1 [default = 12];
    /**
     * <code>required int32 numerical_value = 1 [default = 12];</code>
     */
    boolean hasNumericalValue();
    /**
     * <code>required int32 numerical_value = 1 [default = 12];</code>
     */
    int getNumericalValue();
  }
  /**
   * Protobuf type {@code tc.oc.protobuf.packet.protocols.ExtendingMessage}
   */
  public static final class ExtendingMessage extends
      com.google.protobuf.GeneratedMessage
      implements ExtendingMessageOrBuilder {
    // Use ExtendingMessage.newBuilder() to construct.
    private ExtendingMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExtendingMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExtendingMessage defaultInstance;
    public static ExtendingMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ExtendingMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExtendingMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              numericalValue_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tc.oc.protobuf.packet.protocols.TestExtendingMessage.internal_static_tc_oc_protobuf_packet_protocols_ExtendingMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tc.oc.protobuf.packet.protocols.TestExtendingMessage.internal_static_tc_oc_protobuf_packet_protocols_ExtendingMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage.class, tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ExtendingMessage> PARSER =
        new com.google.protobuf.AbstractParser<ExtendingMessage>() {
      public ExtendingMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExtendingMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExtendingMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 numerical_value = 1 [default = 12];
    public static final int NUMERICAL_VALUE_FIELD_NUMBER = 1;
    private int numericalValue_;
    /**
     * <code>required int32 numerical_value = 1 [default = 12];</code>
     */
    public boolean hasNumericalValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 numerical_value = 1 [default = 12];</code>
     */
    public int getNumericalValue() {
      return numericalValue_;
    }

    private void initFields() {
      numericalValue_ = 12;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNumericalValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, numericalValue_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, numericalValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tc.oc.protobuf.packet.protocols.ExtendingMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tc.oc.protobuf.packet.protocols.TestExtendingMessage.internal_static_tc_oc_protobuf_packet_protocols_ExtendingMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tc.oc.protobuf.packet.protocols.TestExtendingMessage.internal_static_tc_oc_protobuf_packet_protocols_ExtendingMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage.class, tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage.Builder.class);
      }

      // Construct using tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        numericalValue_ = 12;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tc.oc.protobuf.packet.protocols.TestExtendingMessage.internal_static_tc_oc_protobuf_packet_protocols_ExtendingMessage_descriptor;
      }

      public tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage getDefaultInstanceForType() {
        return tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage.getDefaultInstance();
      }

      public tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage build() {
        tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage buildPartial() {
        tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage result = new tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.numericalValue_ = numericalValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage) {
          return mergeFrom((tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage other) {
        if (other == tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage.getDefaultInstance()) return this;
        if (other.hasNumericalValue()) {
          setNumericalValue(other.getNumericalValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNumericalValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 numerical_value = 1 [default = 12];
      private int numericalValue_ = 12;
      /**
       * <code>required int32 numerical_value = 1 [default = 12];</code>
       */
      public boolean hasNumericalValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 numerical_value = 1 [default = 12];</code>
       */
      public int getNumericalValue() {
        return numericalValue_;
      }
      /**
       * <code>required int32 numerical_value = 1 [default = 12];</code>
       */
      public Builder setNumericalValue(int value) {
        bitField0_ |= 0x00000001;
        numericalValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 numerical_value = 1 [default = 12];</code>
       */
      public Builder clearNumericalValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        numericalValue_ = 12;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tc.oc.protobuf.packet.protocols.ExtendingMessage)
    }

    static {
      defaultInstance = new ExtendingMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tc.oc.protobuf.packet.protocols.ExtendingMessage)
    public static final int EXTENDING_MESSAGE_FIELD_NUMBER = 16;
    /**
     * <code>extend .tc.oc.protobuf.packet.protocols.GenericMessage { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        tc.oc.protobuf.packet.protocols.TestGenericMessage.GenericMessage,
        tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage> extendingMessage = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage.getDefaultInstance(),
          0,
          tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage.class,
          tc.oc.protobuf.packet.protocols.TestExtendingMessage.ExtendingMessage.getDefaultInstance());
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tc_oc_protobuf_packet_protocols_ExtendingMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tc_oc_protobuf_packet_protocols_ExtendingMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nJsrc/test/java/tc/oc/protobuf/packet/pr" +
      "otocols/test_extending_message.proto\022\037tc" +
      ".oc.protobuf.packet.protocols\032Hsrc/test/" +
      "java/tc/oc/protobuf/packet/protocols/tes" +
      "t_generic_message.proto\"\256\001\n\020ExtendingMes" +
      "sage\022\033\n\017numerical_value\030\001 \002(\005:\002122}\n\021ext" +
      "ending_message\022/.tc.oc.protobuf.packet.p" +
      "rotocols.GenericMessage\030\020 \002(\01321.tc.oc.pr" +
      "otobuf.packet.protocols.ExtendingMessage" +
      "B7\n\037tc.oc.protobuf.packet.protocolsB\024Tes",
      "tExtendingMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tc_oc_protobuf_packet_protocols_ExtendingMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tc_oc_protobuf_packet_protocols_ExtendingMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tc_oc_protobuf_packet_protocols_ExtendingMessage_descriptor,
              new java.lang.String[] { "NumericalValue", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tc.oc.protobuf.packet.protocols.TestGenericMessage.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
